# Generated by Django 6.0.6 on 2026-06-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_alerta', models.PositiveIntegerField(default=7, verbose_name='Días de alerta antes de vencer')),
            ],
            options={
                'verbose_name': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=100, verbose_name='Código de barra')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad en stock')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
