# Generated by Django 5.2 on 2026-06-14 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_configuracion_id_alter_producto_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProductoDañado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_danio', models.CharField(choices=[('RASGADO', 'Rasgado'), ('ROTO', 'Roto'), ('ECHADO_PERDER', 'Echado a perder'), ('MOJADO', 'Mojado'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de daño')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo/Descripción')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('REVISADO', 'Revisado'), ('DESCARTADO', 'Descartado')], default='REPORTADO', max_length=20, verbose_name='Estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Producto Dañado',
                'verbose_name_plural': 'Productos Dañados',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
