# Generated by Django 5.2 on 2026-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_configuracion_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('foto_url', models.URLField(blank=True, max_length=500)),
                ('foto_archivo', models.ImageField(blank=True, null=True, upload_to='productos_fotos/')),
                ('origen', models.CharField(choices=[('api', 'Open Food Facts'), ('manual', 'Ingresado manualmente')], default='manual', max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de producto',
                'verbose_name_plural': 'Catálogo de productos',
                'ordering': ['nombre'],
            },
        ),
    ]
