# Generated by Django 5.2 on 2026-07-01 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_codigorecuperacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=100, verbose_name='Código de barras')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('tipo_danio', models.CharField(choices=[('rasgado', 'Rasgado / embalagem rasgada'), ('mojado', 'Molhado / úmido'), ('aplastado', 'Amassado / deformado'), ('vencido', 'Vencido (retirado da gôndola)'), ('otro', 'Outro')], max_length=20, verbose_name='Tipo de avaria')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendente de baixa'), ('cerrado', 'Fechado / dado baixa')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Data do reporte')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Avaria',
                'verbose_name_plural': 'Avarias',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.DeleteModel(
            name='ProductoDañado',
        ),
    ]
