# Generated by Django 5.2 on 2026-08-07 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_avaria_delete_productodañado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='revisado',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
